# Начало определения пайплайна
stages:
  - build
  - test
  - package

# Определение переменных
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  DOCKER_IMAGE_TAG: "my-app:latest"

# Определение задач для каждой стадии
build:
  stage: build
  image: maven:3.8.5-openjdk-22
  script:
    - mvn $MAVEN_OPTS clean compile

test:
  stage: test
  image: maven:3.8.5-openjdk-22
  script:
    - mvn $MAVEN_OPTS test

package:
  stage: package
  image: maven:3.8.5-openjdk-22
  script:
    - mvn $MAVEN_OPTS package

  artifacts:
    paths:
      - ./target/*.jar

# Определение деплоймента в Docker
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker run -d -p 8080:8080 $DOCKER_IMAGE_TAG
  only:
    - master  # Деплой только для ветки master

# Определение тестовых задач
integration_test:
  stage: test
  image: maven:3.8.5-openjdk-22
  script:
    - mvn $MAVEN_OPTS verify -Pintegration-tests
